# Generated by Django 5.2.5 on 2025-08-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movieType',
            field=models.CharField(default='Romantic', max_length=100),
        ),
    ]
