# Generated by Django 5.2.5 on 2025-08-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_movietype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movieType',
            new_name='genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, default='movies/default.jpg', null=True, upload_to='movies/'),
        ),
    ]
